### ISSUE TITLE
Request - Please addTp-LSD-Lite trained weight

### ISSUE THREAD

**Issue by ofirkris** [Siyuada7/TP-LSD#1]
Hello,  thanks for sharing your great work - can you also share the more lightweight model for testing purposes?

**Comment by Siyuada7** [comment]
Hi ofirkris,
Thanks for your attention.  All the models used in the paper have been uploaded to the `pretraineds` folder. 
The model selection section has been added to `demo_line.py`. You can now select the model to test by specifying the `--model` parameter, eg. `python demo_line.py img_path --model=tplite --method=tplsd`.
